/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    AppNav: typeof import('./src/components/common/AppNav.vue')['default']
    AppSearch: typeof import('./src/components/common/AppSearch.vue')['default']
    ArticleCard: typeof import('./src/components/article/ArticleCard.vue')['default']
    ArticleList: typeof import('./src/components/articles/ArticleList.vue')['default']
    ArticleStats: typeof import('./src/components/articles/ArticleStats.vue')['default']
    BackToTop: typeof import('./src/components/common/BackToTop.vue')['default']
    Carousel: typeof import('./src/components/common/Carousel.vue')['default']
    CommentSection: typeof import('./src/components/article/CommentSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ErrorMessage: typeof import('./src/components/common/ErrorMessage.vue')['default']
    FeaturedArticles: typeof import('./src/components/common/FeaturedArticles.vue')['default']
    ImageUpload: typeof import('./src/components/common/ImageUpload.vue')['default']
    InfiniteScroll: typeof import('./src/components/common/InfiniteScroll.vue')['default']
    LazyImage: typeof import('./src/components/common/LazyImage.vue')['default']
    LoadingOverlay: typeof import('./src/components/common/LoadingOverlay.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MarkdownEditor: typeof import('./src/components/editor/MarkdownEditor.vue')['default']
    MetaTags: typeof import('./src/components/common/MetaTags.vue')['default']
    Notification: typeof import('./src/components/common/Notification.vue')['default']
    PageTransition: typeof import('./src/components/common/PageTransition.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    Rating: typeof import('./src/components/common/Rating.vue')['default']
    ReadingProgress: typeof import('./src/components/common/ReadingProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultItem: typeof import('./src/components/common/SearchResultItem.vue')['default']
    SearchSuggestions: typeof import('./src/components/common/SearchSuggestions.vue')['default']
    TableOfContents: typeof import('./src/components/article/TableOfContents.vue')['default']
    TagSelect: typeof import('./src/components/common/TagSelect.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
  }
}
